project:
  type: website
  output-dir: _site

website:
  #favicon: file/path/to/image.png
  title: "Jeffrey K. Bye, Ph.D."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: posts.qmd
        text: Posts
      - href: https://edpsych.umn.edu/research/labs/math-learning
        text: Lab
  page-footer:
    background: dark
    right:
      - "© 2024, Jeffrey K. Bye"

format:
  html:
    theme:
      dark: theme-dark.scss
      light: theme-light.scss
    css: styles.css
    mainfont: Inter
    toc: true
    page-layout: full
    include-in-header:
      - includes.html